# inherit_from: rubocop_todo.yml

Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'db/**/*'
    - 'vendor/**/*'
    - 'config/application.rb'
    - 'config/environments/**/*'
    - 'config/initializers/**/*'
    - 'test/test_helper.rb'
    - 'test/support/**/*'
    - 'client/node_modules/**/*'
    - 'lib/tasks/**/*'

HasAndBelongsToMany:
  Enabled: false

Documentation:
  Enabled: false

MethodDefParentheses:
  Enabled: false

GuardClause:
  Enabled: false

RedundantSelf:
  Enabled: false

LineLength:
  Max: 81
  Enabled: true

Style/MethodName:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Metrics/MethodLength:
  Max: 13

Metrics/AbcSize:
  Max: 16

Style/ClassAndModuleChildren:
  Enabled: false

LambdaCall:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/SingleLineMethods:
  Enabled: false

Style/Lambda:
  Enabled: false

HttpPositionalArguments:
  Enabled: false

# only alphabetical sort
Bundler/OrderedGems:
  Enabled: false

SkipsModelValidations:
  Enabled: false
