language: ruby
rvm:
  - 2.3.3
notifications:
  email:
    - dev@clarat.org
before_script:
  - "RAILS_ENV=test bundle exec rake db:migrate"
  - "npm install"
  - "cd client && npm run build:client"
script:
  - RAILS_ENV=test bundle exec rake test:all
before_install:
  - "npm install -g npm@latest"
  - "curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -"
  - "sudo apt-get install -y nodejs"
sudo: required
