language: ruby
rvm:
  - 2.3.3
notifications:
  email:
    - dev@clarat.org
before_script:
  - "RAILS_ENV=test bundle exec rake db:migrate"
  - "npm install"
  - "cd client && npm run build:client"
script:
  - RAILS_ENV=test bundle exec rake test:all
before_install:
  - "npm install -g npm@latest"
sudo: false
