update_statistics_job:
  cron: "0 22 * * * Europe/Berlin" # every day at 22:00
  class: "UpdateStatisticsWorker"
  queue: default

expire_offers_job:
  cron: "0 3 * * * Europe/Berlin" # every day at 03:00
  class: "ExpiringOffersWorker"
  queue: default

regenerate_html_job:
  cron: "50 23 * * Thu Europe/Berlin" # every thursday at 00:00
  class: "RegenerateHtmlWorker"
  queue: default

subscribed_mails_spawner_job:
  cron: "0 20 * * Mon Europe/Berlin" # every (2nd) monday at 20:00
  class: "SubscribedEmailsMailingsSpawnerWorker"
  queue: default

uninformed_mails_spawner_job:
  cron: "30 20 * * 1 Europe/Berlin" # every monday at 20:30
  class: "UninformedEmailsMailingsSpawnerWorker"
  queue: default

# TODO: reactivate!!
# check_websites_job:
#   cron: "0 20 * * Wed Europe/Berlin"
#   class: "CheckWebsitesWorker"
#   queue: heavy_load

check_for_new_translations_job:
  cron: "0 0 * * * Europe/Berlin" # every day at 00:00
  class: "CheckForNewTranslationsWorker"
  queue: heavy_load

check_for_new_contacts_job:
  cron: "0 8,12,15,18 * * * Europe/Berlin" # every day at 8:00, 12:00, 15:00 and 18:00
  class: "CheckForNewContactsWorker"
  queue: default
